apiVersion: apps/v1
kind: Replicaset
metadata:
  name: nginx-1b
  labels:
    app: nginx
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      app: nginx
  template:
    metadata:
      labels:
        tier: frontend
        app: nginx
  spec:
      containers:
      - name: php-redis
        image: us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5